In [57]:
corpus = ['king is a strong man', 
          'queen is a wise woman', 
          'boy is a young man',
          'girl is a young woman',
          'prince is a young king',
          'princess is a young queen',
          'man is strong', 
          'woman is pretty',
          'prince is a boy will be king',
          'princess is a girl will be queen']

In [58]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [60]:
def remove_stopwords(corpus) :
    stopwords = ['is','a','will','be']
    return [[word for word in sent.split() if word not in stopwords] for sent in corpus]

In [62]:
corpus = remove_stopwords(corpus)
corpus

[['king', 'strong', 'man'],
 ['queen', 'wise', 'woman'],
 ['boy', 'young', 'man'],
 ['girl', 'young', 'woman'],
 ['prince', 'young', 'king'],
 ['princess', 'young', 'queen'],
 ['man', 'strong'],
 ['woman', 'pretty'],
 ['prince', 'boy', 'king'],
 ['princess', 'girl', 'queen']]

In [64]:
words = []
for token_sent in corpus :
    words.extend(token_sent)
words = list(set(words))
words

['girl',
 'prince',
 'wise',
 'queen',
 'king',
 'woman',
 'boy',
 'young',
 'strong',
 'man',
 'princess',
 'pretty']

In [67]:
word2index = {word:idx for idx, word in enumerate(words)}
word2index

{'girl': 0,
 'prince': 1,
 'wise': 2,
 'queen': 3,
 'king': 4,
 'woman': 5,
 'boy': 6,
 'young': 7,
 'strong': 8,
 'man': 9,
 'princess': 10,
 'pretty': 11}

In [72]:
WINDOW_SIZE = 2
skip_gram = []
for token_sent in corpus :
    for idx, center in enumerate(token_sent) :
        neighbors = token_sent[max(0, idx-WINDOW_SIZE): min(len(token_sent), idx+WINDOW_SIZE) + 1]
        for neighbor in neighbors :
            if neighbor is not center :
                skip_gram.append((center, neighbor))
skip_gram = pd.DataFrame(skip_gram, columns=('center', 'neighbor'))

In [73]:
skip_gram

      center  neighbor
0       king    strong
1       king       man
2     strong      king
3     strong       man
4        man      king
5        man    strong
6      queen      wise
7      queen     woman
8       wise     queen
9       wise     woman
10     woman     queen
11     woman      wise
12       boy     young
13       boy       man
14     young       boy
15     young       man
16       man       boy
17       man     young
18      girl     young
19      girl     woman
20     young      girl
21     young     woman
22     woman      girl
23     woman     young
24    prince     young
25    prince      king
26     young    prince
27     young      king
28      king    prince
29      king     young
30  princess     young
31  princess     queen
32     young  princess
33     young     queen
34     queen  princess
35     queen     young
36       man    strong
37    strong       man
38     woman    pretty
39    pretty     woman
40    prince       boy
41    prince      king
42       boy    prince
43       boy      king
44      king    prince
45      king       boy
46  princess      girl
47  princess     queen
48      girl  princess
49      girl     queen
50     queen  princess
51     queen      girl

In [74]:
ONE_HOT_DIM = len(words)
EMBED_DIM = 2

In [75]:
from tensorflow.keras.utils import to_categorical
X_train = to_categorical(skip_gram['center'].apply(lambda x : word2index[x]))
y_train = to_categorical(skip_gram['neighbor'].apply(lambda x : word2index[x]))

In [76]:
print(X_train.shape)
print(y_train.shape)

(52, 12)
(52, 12)

In [77]:
#모델링

In [78]:
initializer = tf.initializers.RandomNormal()
W1 = tf.Variable(initializer([ONE_HOT_DIM, EMBED_DIM]))
b1 = tf.Variable(initializer([1]))

In [79]:
b1